### ISSUE TITLE
Check panic during monitoring agent depolyment

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1126]
- 실패한 VM이 포함된, MCIS에 모니터링 에이전트 설치를 내부적으로 실행하는 경우,
 - nil에 의해서 시스템 panic이 발생하는 경우가 있었음.
 - 재현 및 버그 픽스 필요

```
[Start SSH checking squence]
[GetVmSshKey]caaefkgrjs5oo6o7b0b0-0
MonAgentStatus : 
MonAgentStatus : notInstalled
[GetVmIp] caaegiorjs5oo6o7b0gg-0[GetVmIp] caaegborjs5oo6o7b0eg-0ns01-systemdefault-tencent-ap-guangzhou
 8.218.47.51

[GetVmIp] caaeg9grjs5oo6o7b0e0-0[GetVmIp] caaegdgrjs5oo6o7b0f0-0 121.40.213.91

[Start SSH checking squence]
[GetVmSshKey]caaegborjs5oo6o7b0eg-0
 47.101.193.37

[Start SSH checking squence]
[GetVmSshKey]caaegdgrjs5oo6o7b0f0-0
 35.234.50.223

[Start SSH checking squence]
[GetVmSshKey]caaeg9grjs5oo6o7b0e0-0
ns01-systemdefault-alibaba-cn-shanghai
ns01-systemdefault-alibaba-cn-hangzhou
ns01-systemdefault-gcp-asia-east1
[Retrieve ssh username from the given list]
[Check SSH] (47.101.193.37) with userName: cb-user
[Retrieve ssh username from the given list]
[Check SSH] (121.40.213.91) with userName: cb-user
[GetVmIp] caaegf8rjs5oo6o7b0fg-0[Retrieve ssh username from the given list]
[Check SSH] (8.142.188.6) with userName: cb-user
[GetVmIp] caaefkgrjs5oo6o7b0c0-0 1.13.185.93

[Start SSH checking squence]
[GetVmSshKey]caaegf8rjs5oo6o7b0fg-0
 empty

[Start SSH checking squence]
[GetVmSshKey]caaefkgrjs5oo6o7b0c0-0
[Start SSH checking squence]
[GetVmSshKey]caaegiorjs5oo6o7b0gg-0
ns01-systemdefault-alibaba-cn-shenz
ns01-systemdefault-tencent-ap-nanjing
ns01-systemdefault-alibaba-cn-hongkong
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1078df4]

goroutine 572895 [running]:
github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetVmSshKey(0xc0033f7fc3, 0x4, 0xc001afe060, 0x8, 0xc001fb536a, 0x16, 0x0, 0x0, 0xc0021b2c30, 0xc001aa6a58, ...)
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:454 +0x4b4
github.com/cloud-barista/cb-tumblebug/src/core/mcis.VerifySshUserName(0xc0033f7fc3, 0x4, 0xc001afe060, 0x8, 0xc001fb536a, 0x16, 0xc001df9090, 0x5, 0x0, 0x0, ...)
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:347 +0x14c
github.com/cloud-barista/cb-tumblebug/src/core/mcis.CallMonitoringAsync(0xc002d40330, 0xc0033f7fc3, 0x4, 0xc001afe060, 0x8, 0x0, 0x0, 0xc001fb536a, 0x16, 0x15ea174, ...)
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/monitoring.go:181 +0x190
created by github.com/cloud-barista/cb-tumblebug/src/core/mcis.InstallMonitorAgentToMcis
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/monitoring.go:349 +0x9c8
Makefile:12: recipe for target 'run' failed
make: *** [run] Error 2

```

**Comment by seokho-son** [comment]
늘 발생하는 문제는 아닌 것으로 보임.

**Comment by seokho-son** [comment]
해당 버그가 재현되는 경우 다시 오픈 예정.
