### ISSUE TITLE
long-time operation or many VMs may lead a meta db problem

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1131]
**What happened**
8개 MCIS, VM 100개 이상을 제어하는 상황에서,

MCIS의 개별 VM을 삭제한 후, 

- meta DB의 값이 지워지는 상황 발생. 
- 키는 유지됨.

```
http://localhost:1323/tumblebug/ns/ns01
```
```
Response body: {   "id": "",   "name": "",   "description": "" }
```

동일한 현상이 발생하는 MCIS가 있었음.

**How to reproduce it (as minimally and precisely as possible)**

- 재현해보지 않음
- 유사 환경 조성하여 다양한 테스트 필요
- MCIS에서 특정 VM 삭제 테스트

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: Head
- OS: ubuntu
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by seokho-son** [comment]
// GenMcisKey is func to generate a key used in keyValue store
func GenMcisKey(nsId string, mcisId string, vmId string) string {

	if vmId != "" {
		return "/ns/" + nsId + "/mcis/" + mcisId + "/vm/" + vmId
	} else if mcisId != "" {
		return "/ns/" + nsId + "/mcis/" + mcisId
	} else if nsId != "" {
		return "/ns/" + nsId
	} else {
		return ""
	}

}
error handling 보완 필요.

**Comment by seokho-son** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47d44b]

goroutine 1033235 [running]:
github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetVmStatusAsync(0xc000e5bc20, 0xc001c6fc12, 0x4, 0xc003a0810e, 0x12, 0xc00184c664, 0x16, 0xc0000dd440, 0x0, 0x0)
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/manageInfo.go:907 +0x28f
created by github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetMcisStatus
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/manageInfo.go:533 +0x6a9
Makefile:12: recipe for target 'run' failed
make: *** [run] Error 2
```

**Comment by seokho-son** [comment]
MCIS 수를 300개까지 올려보면,

Spider와의 connection 이슈로, hitting the default limit of 1024 "open files 발생함.

관련 솔루션:

https://blog.sensecodons.com/2022/04/golang-httpclient-and-too-many-open.html

**Comment by seokho-son** [comment]
미봉책: change max file descriptors

https://stackoverflow.com/questions/32325343/go-tcp-too-many-open-files-debug

**Comment by seokho-son** [comment]
https://yongho1037.tistory.com/815

**Comment by seokho-son** [comment]
고루틴 버퍼드 채널 사용 또는 
Rate 제한도 방안이 될 수 있음.

https://dev.to/godoylucase/rate-limiting-your-goroutines-1om1
