### ISSUE TITLE
Provisioning Global L4 NLB faces runtime error

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1362]
**What happened**
: Global L4 NLB 생성시, 런타임 애러 발생

**How to reproduce it (as minimally and precisely as possible)**
: Global L4 NLB 생성

**Anything else we need to know?**
```
goroutine 10059 [running]:
github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetVmIp({0xc0013284d3, 0x4}, {0xc000c7c730, 0xa}, {0xc000dc11b8, 0x4})
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/manageInfo.go:1040 +0x2aa
github.com/cloud-barista/cb-tumblebug/src/core/mcis.RunRemoteCommand({0xc0013284d3, 0x4}, {0xc000c7c730, 0xa}, {0xc000cd390c, 0x5}, {0x0, 0x0}, {0xc001156120, 0x1, ...})
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:182 +0x193
github.com/cloud-barista/cb-tumblebug/src/core/mcis.RunRemoteCommandAsync(0x0?, {0xc0013284d3, 0x4}, {0xc000c7c730, 0xa}, {0xc000cd390c, 0x5}, {0x0, 0x0}, {0xc001156120, ...}, ...)
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:222 +0x13e
created by github.com/cloud-barista/cb-tumblebug/src/core/mcis.RemoteCommandToMcis
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:160 +0x791
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xddffea]

goroutine 10060 [running]:
github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetVmIp({0xc0013284d3, 0x4}, {0xc000c7c730, 0xa}, {0xc000e7b538, 0x4})
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/manageInfo.go:1040 +0x2aa
github.com/cloud-barista/cb-tumblebug/src/core/mcis.RunRemoteCommand({0xc0013284d3, 0x4}, {0xc000c7c730, 0xa}, {0xc000cd393c, 0x5}, {0x0, 0x0}, {0xc001156120, 0x1, ...})
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:182 +0x193
github.com/cloud-barista/cb-tumblebug/src/core/mcis.RunRemoteCommandAsync(0x0?, {0xc0013284d3, 0x4}, {0xc000c7c730, 0xa}, {0xc000cd393c, 0x5}, {0x0, 0x0}, {0xc001156120, ...}, ...)
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:222 +0x13e
created by github.com/cloud-barista/cb-tumblebug/src/core/mcis.RemoteCommandToMcis
	/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/remoteCommand.go:160 +0x791
Makefile:8: recipe for target 'run' failed
make: *** [run] Error 2
```

**Environment**
- Source version or branch: main

**Proposed solution**
: NLB 생성시, remoteCommand를 사용하는데, 최근 추가된 bastion node 특징이 영향을 줄 수 있음. 런타임 디버깅 필요.

**Comment by seokho-son** [comment]
MCIS간 subnet (및 vnet) 공유 모드에서, bastion node의 위치에 의해서 발생하는 오류임.
