### ISSUE TITLE
Create VM in specified MCIS

### ISSUE THREAD

**Issue by vlatte** [cloud-barista/cb-tumblebug#295]
VM 생성 시 아래와 같은 오류가 나며 등록이 되지 않습니다.
원인이 무엇인지 확인 가능할까요?

```
{"message":"Internal Server Error"}
```

생성 테스트 
```
curl -sX POST http://localhost:1323/tumblebug/ns/cb-gcp-namespace/mcis/cluster-test-9/vm  -H "Authorization: Basic $(echo -n default:default | base64)" -H "Content-Type: application/json" -d \
	'{
		"name": "cb-gcp-cluster-test-9-w-29kyy",
		"imageId": "cb-gcp-config-Ubuntu1804",
		"vmUserAccount": "cb-user",
		"connectionName": "cb-gcp-config", 
		"sshKeyId": "cluster-test-9-sshkey",
		"specId": "cluster-test-9-spec",
		"securityGroupIds": ["cluster-test-9-allow-external"],
		"vNetId": "cluster-test-9-vpc",
		"subnetId": "cluster-test-9-vpc-subnet",
		"description": "description",
		"vmUserPassword": ""
	}'
```

로그
```
[API request!]
[Check ns] cb-gcp-namespace
{"time":"2020-10-29T02:31:17.983780123Z","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] reflect: Elem of invalid type mcis.TbVmInfo goroutine 4598 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0x119e650, 0x1000, 0x0, 0x1310b80, 0xc000198460)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/recover.go:71 +0xee\npanic(0xf8fd00, 0xc00090ac10)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\nreflect.(*rtype).Elem(0x111c7c0, 0x0, 0x0)\n\t/usr/local/go/src/reflect/type.go:912 +0x198\ngithub.com/labstack/echo/v4.(*DefaultBinder).bindData(0x23e28b0, 0x111c7c0, 0xc0000f6400, 0xc000572e88, 0x1135aa9, 0x5, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/bind.go:90 +0x9a\ngithub.com/labstack/echo/v4.(*DefaultBinder).Bind(0x23e28b0, 0x111c7c0, 0xc0000f6400, 0x1310b80, 0xc000198460, 0xc0000f6400, 0xc0000f6400)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/bind.go:43 +0x2a5\ngithub.com/labstack/echo/v4.(*context).Bind(0xc000198460, 0x111c7c0, 0xc0000f6400, 0xc0000f6400, 0xe)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/context.go:402 +0x63\ngithub.com/cloud-barista/cb-tumblebug/src/api/rest/server/mcis.RestPostMcisVm(0x1310b80, 0xc000198460, 0x1, 0x0)\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/api/rest/server/mcis/control.go:807 +0x174\ngithub.com/cloud-barista/cb-tumblebug/src/common.NsValidation.func1.1(0x1310b80, 0xc000198460, 0x0, 0xc00003a14d)\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/common/namespace.go:39 +0x23c\ngithub.com/labstack/echo/v4.(*Echo).add.func1(0x1310b80, 0xc000198460, 0xc00098db58, 0x7)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:512 +0x8a\ngithub.com/labstack/echo/v4/middleware.BasicAuthWithConfig.func1.1(0x1310b80, 0xc000198460, 0x114c297, 0x1b)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/basic_auth.go:89 +0x4d1\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0x1310b80, 0xc000198460, 0x0, 0xc0005089d8)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/cors.go:121 +0x477\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1(0x1310b80, 0xc000198460, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/recover.go:78 +0x12a\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0x1310b80, 0xc000198460, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/logger.go:117 +0x130\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000c1e0, 0x12f2360, 0xc0000f2460, 0xc0000ea800)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:623 +0x16c\nnet/http.serverHandler.ServeHTTP(0xc0000f21c0, 0x12f2360, 0xc0000f2460, 0xc0000ea800)\n\t/usr/local/go/src/net/http/server.go:2836 +0xa3\nnet/http.(*conn).serve(0xc0001983c0, 0x12f5a60, 0xc000041680)\n\t/usr/local/go/src/net/http/server.go:1924 +0x86c\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2962 +0x35c\n\ngoroutine 1 [semacquire, 4361 minutes]:\nsync.runtime_Semacquire(0xc0009061c8)\n\t/usr/local/go/src/runtime/sema.go:56 +0x42\nsync.(*WaitGroup).Wait(0xc0009061c0)\n\t/usr/local/go/src/sync/waitgroup.go:130 +0x64\nmain.main()\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/main.go:153 +0x69b\n\ngoroutine 6 [sleep]:\ntime.Sleep(0x77359400)\n\t/usr/local/go/src/runtime/time.go:188 +0xba\ngithub.com/cloud-barista/cb-log.levelSetupLoop(0x113daac, 0xd)\n\t/go/pkg/mod/github.com/cloud-barista/cb-log@v0.1.1/cblogger.go:78 +0x5a\ncreated by github.com/cloud-barista/cb-log.setup\n\t/go/pkg/mod/github.com/cloud-barista/cb-log@v0.1.1/cblogger.go:61 +0xf0\n\ngoroutine 7 [select, 2 minutes]:\ngoogle.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0000414c0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.21.1/balancer_conn_wrappers.go:115 +0x10f\ncreated by google.golang.org/grpc.newCCBalancerWrapper\n\t/go/pkg/mod/google.golang.org/grpc@v1.21.1/balancer_conn_wrappers.go:106 +0x169\n\ngoroutine 50 [chan receive]:\nmain.main.func1(0xc00008c1e0)\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/main.go:53 +0x138\ncreated by main.main\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/main.go:52 +0x1b2\n\ngoroutine 18 [select, 2 minutes]:\ngoogle.golang.org/grpc.(*addrConn).resetTransport(0xc00013e2c0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.21.1/clientconn.go:1058 +\n"}
{"time":"2020-10-29T02:31:17.983960501Z","id":"","remote_ip":"127.0.0.1","host":"localhost:1323","method":"POST","uri":"/tumblebug/ns/cb-gcp-namespace/mcis/cluster-test-9/vm","user_agent":"curl/7.64.1","status":500,"error":"","latency":581071,"latency_human":"581.071µs","bytes_in":426,"bytes_out":36}
```

**Comment by jihoon-seo** [comment]
안녕하세요
다음의 Tumblebug object 들을 생성할 때 사용하셨던 커맨드를 기재해 주시면
재현하여 확인해 보겠습니다.

1. NS
2. Image
3. Spec
4. SSH key
5. vNet
6. Security Group

---

커맨드 예시:
이 이슈의 본문에 적으신 형태와 동일하게 기재해 주시면 되겠습니다.

```
curl -sX POST http://localhost:1323/tumblebug/ns/cb-gcp-namespace/mcis/cluster-test-9/vm  -H "Authorization: Basic $(echo -n default:default | base64)" -H "Content-Type: application/json" -d \
	'{
		"name": "cb-gcp-cluster-test-9-w-29kyy",
		"imageId": "cb-gcp-config-Ubuntu1804",
		"vmUserAccount": "cb-user",
		"connectionName": "cb-gcp-config", 
		"sshKeyId": "cluster-test-9-sshkey",
		"specId": "cluster-test-9-spec",
		"securityGroupIds": ["cluster-test-9-allow-external"],
		"vNetId": "cluster-test-9-vpc",
		"subnetId": "cluster-test-9-vpc-subnet",
		"description": "description",
		"vmUserPassword": ""
	}'
```

**Comment by seokho-son** [comment]
@vlatte 
혹시 MCIS 가 만들어져 있는 상황에서 해당 명령 실행하신 것인지요?

해당 명령어는 기존에 만들어진 MCIS가 있는 경우, MCIS에 요청한 VM을 1개 추가하는 명령어 입니다. 
MCIS 가 없는 경우, VM이 추가가 되지 않습니다. 우선, MCIS를 하나 생성한 후 MCIS ID를 활요하여 VM 추가 기능을 사용하시는 것이 좋을 것 같습니다. (어쨌든 서버 애러가 나오면 안되는데, 문제 되는 부분은 디버깅을 해보도록 하겠습니다.. ^^)

텀블벅은 VM이 1개를 만들더라도 MCIS 오브젝트안에 포함시켜야 합니다.. ^^ VM이 1개 필요한 경우, VM이 1개 포함된 MCIS를 생성하시면 됩니다.

**Comment by seokho-son** [comment]
해당 이슈는 일단 Close 하도록 하겠습니다.. ^^ 
혹시 추가적으로 어려움이 있으시면 다시 이슈를 열어주시거나, 슬랙을 통해서 문의 부탁드립니다! ^^ 감사합니다.
