### ISSUE TITLE
When terminating MCIS, 'runtime error' is occurred

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#296]
cb-webtool 동작 테스트를 하면서 발생한 에러입니다. 명확한 시나리오를 따라서 테스트하진 않아서 재현될지는 모르겠습니다. 가볍게 관련 코드를 검토하시면 좋겠습니다.
참고로 cblogs.log에 특별한 내용은 없어 보였습니다.

o Version: v0.2.0-cappucino

```
cb-tumblebug                 | [API request!]
cb-tumblebug                 | [Check ns] cb-aws-namespace
cb-tumblebug                 | [CLOUD-BARISTA].[INFO]: 2020-10-29 05:48:11 nutsdb-driver.go:125, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.(*NUTSDBDriver).Get() - Key:/ns/cb-aws-namespace
cb-tumblebug                 | [Delete MCIS] cb-aws-config-developer
cb-tumblebug                 | [controlMcis]cb-aws-config-developer to Terminate
cb-tumblebug                 | /ns/cb-aws-namespace/mcis/cb-aws-config-developer
cb-tumblebug                 | [CLOUD-BARISTA].[INFO]: 2020-10-29 05:48:11 nutsdb-driver.go:125, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.(*NUTSDBDriver).Get() - Key:/ns/cb-aws-namespace/mcis/cb-aws-config-develo
per
cb-tumblebug                 | {"time":"2020-10-29T05:48:11.573174812Z","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine
 8501 [running]:\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0xd15f10, 0x1000, 0x0, 0xe16ce0, 0xc00029a7e0)\n\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/recover.go:71 +0xee\npanic(0xbed
320, 0x13501e0)\n\t/usr/local/go/src/runtime/panic.go:967 +0x166\ngithub.com/cloud-barista/cb-tumblebug/src/mcis.controlMcis(0xc000034335, 0x10, 0xc00003434b, 0x17, 0xcdc208, 0x9, 0x0, 0x0)\n\t/go/src/github.com/cloud-barista/cb-tumb
lebug/src/mcis/control.go:2290 +0x29f\ngithub.com/cloud-barista/cb-tumblebug/src/mcis.delMcis(0xc000034335, 0x10, 0xc00003434b, 0x17, 0x17, 0x0)\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/mcis/control.go:1775 +0x135\ngithub
.com/cloud-barista/cb-tumblebug/src/mcis.RestDelMcis(0xe16ce0, 0xc00029a7e0, 0x1, 0x0)\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/mcis/control.go:686 +0xc5\ngithub.com/cloud-barista/cb-tumblebug/src/common.NsValidation.func
1.1(0xe16ce0, 0xc00029a7e0, 0x10, 0xbb0760)\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/common/namespace.go:59 +0x23c\ngithub.com/labstack/echo.(*Echo).Add.func1(0xe16ce0, 0xc00029a7e0, 0xce9397, 0x1b)\n\t/go/pkg/mod/github.
com/labstack/echo@v3.3.10+incompatible/echo.go:490 +0x8a\ngithub.com/labstack/echo/middleware.CORSWithConfig.func1.1(0xe16ce0, 0xc00029a7e0, 0x203000, 0xc0000789c8)\n\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middlew
are/cors.go:117 +0x407\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0xe16ce0, 0xc00029a7e0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/recover.go:78 +0x12a\ngithub.com/labstack
/echo/middleware.LoggerWithConfig.func2.1(0xe16ce0, 0xc00029a7e0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/logger.go:118 +0x130\ngithub.com/labstack/echo.(*Echo).ServeHTTP(0xc00015e1e0, 0xe029
80, 0xc0004ce0e0, 0xc0000fa500)\n\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:593 +0x222\nnet/http.serverHandler.ServeHTTP(0xc000136380, 0xe02980, 0xc0004ce0e0, 0xc0000fa500)\n\t/usr/local/go/src/net/http/serve
r.go:2807 +0xa3\nnet/http.(*conn).serve(0xc0002160a0, 0xe04700, 0xc00020d2c0)\n\t/usr/local/go/src/net/http/server.go:1895 +0x86c\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2933 +0x35c\n\ngoroutine 1
 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f5dfafd5ca8, 0x72, 0x0)\n\t/usr/local/go/src/runtime/netpoll.go:203 +0x55\ninternal/poll.(*pollDesc).wait(0xc0000f8b98, 0x72, 0x0, 0x0, 0xcda579)\n\t/usr/local/go/src/internal/poll/fd_po
ll_runtime.go:87 +0x45\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Accept(0xc0000f8b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/internal/poll/
fd_unix.go:384 +0x1d4\nnet.(*netFD).accept(0xc0000f8b80, 0x203000, 0x203000, 0x203000)\n\t/usr/local/go/src/net/fd_unix.go:238 +0x42\nnet.(*TCPListener).accept(0xc000288760, 0xc0002bbad0, 0x40c246, 0xc0002160a0)\n\t/usr/local/go/src/
net/tcpsock_posix.go:139 +0x32\nnet.(*TCPListener).AcceptTCP(0xc000288760, 0x95c0e722a4882240, 0xc0002bbaa8, 0x4535d9)\n\t/usr/local/go/src/net/tcpsock.go:248 +0x65\ngithub.com/labstack/echo.tcpKeepAliveListener.Accept(0xc000288760,
0xc0002bbad0, 0x4c35f6, 0x5f9a579b, 0x43d43e)\n\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:767 +0x2f\nnet/http.(*Server).Serve(0xc000136380, 0xe01f00, 0xc0000bca78, 0x0, 0x0)\n\t/usr/local/go/src/net/http/serv
er.go:2901 +0x25d\ngithub.com/labstack/echo.(*Echo).StartServer(0xc00015e1e0, 0xc000136380, 0x3, 0xced629)\n\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:663 +0x385\ngithub.com/labstack/echo.(*Echo).Start(...)\n
\t/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:604\ngithub.com/cloud-barista/cb-tumblebug/src/apiserver.ApiServer()\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/apiserver/apiserver.go:217 +0x1f92\nmain.ma
in()\n\t/go/src/github.com/cloud-barista/cb-tumblebug/src/mcism.go:53 +0xc2\n\ngoroutine 18 [sleep]:\ntime.Sleep(0x77359400)\n\t/usr/local/go/src/runtime/time.go:188 +0xba\ngithub.com/cloud-barista/cb-log.levelSetup\n"}
cb-tumblebug                 | {"time":"2020-10-29T05:48:11.573362819Z","id":"","remote_ip":"172.19.0.1","host":"localhost:1323","method":"DELETE","uri":"/tumblebug/ns/cb-aws-namespace/mcis/cb-aws-config-developer","user_agent":"curl
/7.58.0","status":500,"error":"","latency":1304494,"latency_human":"1.304494ms","bytes_in":0,"bytes_out":36}
cb-tumblebug                 | [CLOUD-BARISTA].[INFO]: 2020-10-29 05:48:22 nutsdb-driver.go:151, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.(*NUTSDBDriver).GetList() - Key:/ns
cb-tumblebug                 | Tick at 2020-10-29 05:48:22.888771841 +0000 UTC m=+156240.005707016
cb-tumblebug                 | [List ns]
cb-tumblebug                 | /ns
cb-tumblebug                 | <cb-aws-namespace>
cb-tumblebug                 |
cb-tumblebug                 | ===============================================
```

**Comment by sykim-etri** [comment]
해당 상황에서 v0.2.5 버전를 실행하였을 때는 에러 핸들링(정상 에러 출력)을 하는 것을 확인하였습니다.
