### ISSUE TITLE
`ListVmId` returns not-prefix-trimmed vmID

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#546]
Related issue: #541

**What happened**
: 
정상적이지 않은 TB VM object 가 있음.

http://52.197.30.208:1323/tumblebug/ns/ns-01/mcis/mzc01-import/vm/mzc01-c-1-1yn8c

```JSON
{
  "id": "mzc01-c-1-1yn8c",
  "name": "mzc01-c-1-1yn8c",
  "vmGroupId": "",
  "location": {
    "latitude": "46.1500",
    "longitude": "-123.8800",
    "briefAddr": "Oregon",
    "cloudType": "aws",
    "nativeRegion": "us-west-2"
  },
  "status": "Failed",
  "targetStatus": "Running",
  "targetAction": "Create",
  "monAgentStatus": "",
  "systemMessage": "{\"message\":\"vm-mzc01-c-1-1yn8c already exists!\"}\n",
  "createdTime": "",
  "label": "",
  "description": "",
  "region": {
    "Region": "",
    "Zone": ""
  },
  "publicIP": "",
  "sshPort": "0",
  "publicDNS": "Not assigned yet",
  "privateIP": "",
  "privateDNS": "",
  "vmBootDisk": "",
  "vmBlockDisk": "",
  "connectionName": "mzc-us-west-2-conn-01",
  "specId": "t2-small-spec",
  "imageId": "mzc-us-west-2-conn-01-us-west-2-ubuntu1804",
  "vNetId": "mzc01-aws-vpc",
  "subnetId": "mzc01-aws-vpc-subnet",
  "securityGroupIds": [
    "mzc01-aws-allow-external"
  ],
  "sshKeyId": "mzc01-aws-sshkey",
  "vmUserAccount": "",
  "vmUserPassword": "",
  "cspViewVmDetail": {
    "Name": "",
    "ImageName": "",
    "VPCName": "",
    "SubnetName": "",
    "SecurityGroupNames": null,
    "KeyPairName": "",
    "VMSpecName": "",
    "VMUserId": "",
    "VMUserPasswd": "",
    "IId": {
      "NameId": "",
      "SystemId": ""
    },
    "ImageIId": {
      "NameId": "",
      "SystemId": ""
    },
    "VpcIID": {
      "NameId": "",
      "SystemId": ""
    },
    "SubnetIID": {
      "NameId": "",
      "SystemId": ""
    },
    "SecurityGroupIIds": null,
    "KeyPairIId": {
      "NameId": "",
      "SystemId": ""
    },
    "StartTime": "0001-01-01T00:00:00Z",
    "Region": {
      "Region": "",
      "Zone": ""
    },
    "NetworkInterface": "",
    "PublicIP": "",
    "PublicDNS": "",
    "PrivateIP": "",
    "PrivateDNS": "",
    "VMBootDisk": "",
    "VMBlockDisk": "",
    "SSHAccessPoint": "",
    "KeyValueList": null
  }
}
```

이 상태에서 "List MCIS" API 를 실행하면 panic 발생
http://52.197.30.208:1323/tumblebug/ns/ns-01/mcis
```JSON
{"message":"Internal Server Error"}
```
(원래는 panic: runtime error: invalid memory address or nil pointer dereference 발생하고 TB 강제종료 됐었는데
CB-WIP 환경에 defer-recover 구문을 넣어서 강제종료 되지 않도록 해 놓았음)

TB 로그 메시지는 다음과 같음
```
[GetVmObject] mcisId: mzc01, vmId:/ns/ns-01/mcis/mzc01-import/vm/mzc01-c-1-1yn8c
[CLOUD-BARISTA].[INFO]: 2021-05-25 08:53:29 nutsdb-driver.go:132, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.(*NUTSDBDriver).Get() - Key:/ns/ns-01/mcis/mzc01/vm//ns/ns-01/mcis/mzc01-import/vm/mzc01-c-1-1yn8c
{"time":"2021-05-25T08:53:29.32117442Z","level":"-","prefix":"echo","file":"recover.go","line":"92","message":"[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 100 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0x1501048, 0x1000, 0x0, 0x16591a8, 0xc00429e960)\n\t/root/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/middleware/recover.go:77 +0x105\npanic(0x12d0280, 0x1f85ad0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/cloud-barista/cb-tumblebug/src/core/mcis.GetVmObject(0xc00024c252, 0x5, 0xc0025feccf, 0x5, 0xc0001dc660, 0x2e, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/cb-tumblebug/src/core/mcis/control.go:3798 +0x279\ngithub.com/cloud-barista/cb-tumblebug/src/core/mcis.GetMcisStatus(0xc00024c252, 0x5, 0xc0025feccf, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/cb-tumblebug/src/core/mcis/control.go:3686 +0x87e\ngithub.com/cloud-barista/cb-tumblebug/src/core/mcis.CoreGetAllMcis(0xc00024c252, 0x5, 0x146b08d, 0x6, 0x1, 0x27, 0x0, 0x0, 0x461807)\n\t/root/cb-tumblebug/src/core/mcis/control.go:1608 +0xdfc\ngithub.com/cloud-barista/cb-tumblebug/src/api/rest/server/mcis.RestGetAllMcis(0x16591a8, 0xc00429e960, 0x1, 0x0)\n\t/root/cb-tumblebug/src/api/rest/server/mcis/control.go:163 +0x1b6\ngithub.com/cloud-barista/cb-tumblebug/src/core/common.NsValidation.func1.1(0x16591a8, 0xc00429e960, 0x1, 0x1)\n\t/root/cb-tumblebug/src/core/common/namespace.go:48 +0x3cd\ngithub.com/labstack/echo/v4.(*Echo).add.func1(0x16591a8, 0xc00429e960, 0xc00416e3e8, 0x7)\n\t/root/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/echo.go:536 +0x62\ngithub.com/labstack/echo/v4/middleware.BasicAuthWithConfig.func1.1(0x16591a8, 0xc00429e960, 0x0, 0x0)\n\t/root/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/middleware/basic_auth.go:89 +0x4cc\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0x16591a8, 0xc00429e960, 0x0, 0x7f50a45bc6d0)\n\t/root/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/middleware/cors.go:118 +0x15a5\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1(0x16591a8, 0xc00429e960, 0x0, 0x0)\n\t/root/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/middleware/recover.go:98 +0x142\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0x16591a8, 0xc00429e960, 0x0, 0x0)\n\t/root/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/middleware/logger.go:117 +0x12c\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc004172000, 0x163e490, 0xc0003f62a0, 0xc001640700)\n\t/root/go/pkg/mod/github.com/labstack/echo/v4@v4.3.0/echo.go:646 +0x2bc\nnet/http.serverHandler.ServeHTTP(0xc0003f6000, 0x163e490, 0xc0003f62a0, 0xc001640700)\n\t/usr/local/go/src/net/http/server.go:2887 +0xa3\nnet/http.(*conn).serve(0xc0007bb0e0, 0x1641598, 0xc0003c0640)\n\t/usr/local/go/src/net/http/server.go:1952 +0x8cd\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3013 +0x39b\n\ngoroutine 1 [semacquire, 18 minutes]:\nsync.runtime_Semacquire(0xc0007ac228)\n\t/usr/local/go/src/runtime/sema.go:56 +0x45\nsync.(*WaitGroup).Wait(0xc0007ac220)\n\t/usr/local/go/src/sync/waitgroup.go:130 +0x65\nmain.main()\n\t/root/cb-tumblebug/src/main.go:134 +0x8f7\n\ngoroutine 6 [sleep]:\ntime.Sleep(0x77359400)\n\t/usr/local/go/src/runtime/time.go:193 +0xd2\ngithub.com/cloud-barista/cb-log.levelSetupLoop(0x1471f7c, 0xd, 0x0, 0x0)\n\t/root/go/pkg/mod/github.com/cloud-barista/cb-log@v0.3.1/cblogger.go:88 +0x5a\ncreated by github.com/cloud-barista/cb-log.setup\n\t/root/go/pkg/mod/github.com/cloud-barista/cb-log@v0.3.1/cblogger.go:71 +0x125\n\ngoroutine 10 [chan receive, 18 minutes]:\ngopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc000094360)\n\t/root/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x5d\ncreated by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1\n\t/root/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0x75\n\ngoroutine 41 [select, 18 minutes]:\ndatabase/sql.(*DB).connectionOpener(0xc0000aa820, 0x16414f0, 0xc000052380)\n\t/usr/local/go/src/database/sql/sql.go:1133 +0xb5\ncreated by database/sql.OpenDB\n\t/usr/local/go/src/database/sql/sql.go:740 +0x12a\n\ngoroutine 42 [chan receive]:\nmain.main.func1(0xc0007b8140)\n\t/root/cb-tumblebug/src/main.go:108 +0x6b\ncreated by main.main\n\t/root/cb-tumblebug/src/main.go:107 +0x855\n\ngoroutine 43 [IO wait, 5 minutes]:\ninternal/poll.runtime_pollW\n"}
{"time":"2021-05-25T08:53:29.321293676Z","id":"","remote_ip":"129.254.75.178","host":"52.197.30.208:1323","method":"GET","uri":"/tumblebug/ns/ns-01/mcis","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","status":500,"error":"","latency":5582835785,"latency_human":"5.582835785s","bytes_in":0,"bytes_out":36}
```

[Call chain]
- `GetVmObject`
- `GetMcisStatus`
- `CoreGetAllMcis`
- `RestGetAllMcis`

[주목할 점]
- `GetVmObject` 가 호출됐을 때, `GetVmObject` 의 인자로
mcisId: `mzc01` 이라고 왔고
vmId: `mzc01-c-1-1yn8c` 이라고 왔어야 했는데
vmId: `/ns/ns-01/mcis/mzc01-import/vm/mzc01-c-1-1yn8c` 이라고 왔음.
- `GetVmObject` 을 호출한 것은 `GetMcisStatus` 이므로, `GetMcisStatus` 를 살펴 봐야 함.
- `GetMcisStatus` 에서는 `ListVmId(nsId, mcisId)` 함수를 이용해 `vmList` 를 가져오고
`vmList` 에 있는 `vmId` 들에 대해 `GetVmObject(nsId, mcisId, v)` 를 실행함.
- `ListVmId` 함수가
`mzc01-c-1-1yn8c` 형태로 리턴했어야 하는데
`/ns/ns-01/mcis/mzc01-import/vm/mzc01-c-1-1yn8c` 형태로 리턴한 것으로 추정됨.

[참고: `func ListVmId()`]
```Golang
func ListVmId(nsId string, mcisId string) ([]string, error) {

	nsId = strings.ToLower(nsId)
	err := common.CheckString(nsId)
	if err != nil {
		common.CBLog.Error(err)
		return nil, err
	}
	mcisId = strings.ToLower(mcisId)
	err = common.CheckString(mcisId)
	if err != nil {
		common.CBLog.Error(err)
		return nil, err
	}

	fmt.Println("[ListVmId]")
	key := common.GenMcisKey(nsId, mcisId, "")
	//fmt.Println(key)

	keyValue, err := common.CBStore.GetList(key, true)

	if err != nil {
		common.CBLog.Error(err)
		return nil, err
	}
	var vmList []string
	for _, v := range keyValue {
		if strings.Contains(v.Key, "/vm/") {
			vmList = append(vmList, strings.TrimPrefix(v.Key, (key+"/vm/")))
		}
	}
	/*
		for _, v := range vmList {
			fmt.Println("<" + v + ">")
		}
		fmt.Println("===============================================")
	*/
	return vmList, nil

}
```

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by jihoon-seo** [comment]
[확인 2]
`ListVmId` 함수를 호출하는 REST API를 만들어서 테스트 해 보니, 
`ListVmId` 함수의 결과값에는 문제가 없음

GET `http://192.168.1.10:1323/tumblebug/ns/ns-01/mcis/mzc01-import/testListVmId`

```JSON
["mzc01-c-1-1yn8c","mzc01-c-2-49ufn","mzc01-c-3-7zhex","mzc01-w-1-2ga0i","mzc01-w-2-2o7a7","mzc01-w-3-a1krn","mzc01-w-3-a1krn2"]
```

**Comment by jihoon-seo** [comment]
`ListVmId` 함수에 문제가 있는 것이 아니라,
Tumblebug meta DB에
`"id": "/ns/ns-01/mcis/mzc01-import/vm/mzc01-w-3-a1krn2"` 인 VM이 생성되어 있어서
이 현상이 발생한 것으로 확인되었습니다.
